spring:
  application:
    name: MessageApp
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000   # Cierra conexiones inactivas después de 30s
      max-lifetime: 1800000  # 30 min (menor que el timeout de PostgreSQL)
      keepalive-time: 300000
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:5173/google/callback/
            scope: openid,profile,email
        provider:
         google:
            issuer-uri: https://accounts.google.com
firebase:
  credentials:
    path: firebase-credentials.json